checksumBehavior: update

enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

# Satisfy peer deps that are provided by other workspaces or optional at install time
packageExtensions:
  "react-hot-toast@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "burner-connector@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      "@tanstack/react-query": "*"
  "@react-native-async-storage/async-storage@*":
    peerDependenciesMeta:
      react-native:
        optional: true
  "kubo-rpc-client@*":
    peerDependenciesMeta:
      undici:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
