// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title   IZKVerifier
 * @notice  Minimal interface every ZK verifier contract must implement.
 *          Compatible with Groth16 and PLONK verifier conventions as
 *          generated by SnarkJS (`snarkjs generateverifier`).
 *
 * @dev     The auto-generated SnarkJS verifier exposes:
 *            function verifyProof(
 *                uint[2] calldata _pA,
 *                uint[2][2] calldata _pB,
 *                uint[2] calldata _pC,
 *                uint[2] calldata _pubSignals
 *            ) public view returns (bool)
 *
 *          EvidenceVault wraps this via `encodeProof()` helper in the
 *          client SDK and passes the encoded bytes here.
 */
interface IZKVerifier {

    /**
     * @notice Verify a Groth16 zk-SNARK proof.
     *
     * @param  proofData     ABI-encoded Groth16 proof components:
     *                       abi.encode(
     *                           uint256[2] pA,       // G1 point
     *                           uint256[2][2] pB,    // G2 point
     *                           uint256[2] pC        // G1 point
     *                       )
     *
     * @param  publicInputs  Array of public signal field elements.
     *                       For CommitmentProof circuit:
     *                         [0] = fileHash   (as BN254 field element)
     *                         [1] = commitment (as BN254 field element)
     *
     * @return valid         True if the proof is valid for the given public inputs.
     */
    function verifyProof(
        bytes     calldata proofData,
        uint256[] calldata publicInputs
    ) external view returns (bool valid);
}
