name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [lts/*]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node env
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Compile contracts & generate TypeScript ABIs
        run: yarn hardhat:compile

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0

      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0

      - name: Check types
        run: yarn next:check-types

      - name: Build nextjs (type-check + build)
        run: yarn next:build

        # LTS version